import sqlite3
conn = sqlite3.connect('order.db')
CREATE TABLE menu (id INTEGER PRIMARY KEY, name char(100) NOT NULL, quantity INTEGER);
INSERT INTO menu (name, quantity) VALUES ('one', 0 );
INSERT INTO menu (name, quantity) VALUES ('$toned', 0 );
INSERT INTO menu (name, quantity) VALUES ('three', 0 );
INSERT INTO menu (name, quantity) VALUES ('four', 0 );
INSERT INTO menu (name, quantity) VALUES ('five', 0 );
INSERT INTO menu (name, quantity) VALUES ('six', 0 );
INSERT INTO menu (name, quantity) VALUES ('seven', 0 );
INSERT INTO menu (name, quantity) VALUES ('?', 0 );
INSERT INTO menu (name, quantity) VALUES ('Regular', 0 );
INSERT INTO menu (name, quantity) VALUES ('Classic', 0 );
INSERT INTO menu (name, quantity) VALUES ('Cali', 0 );
INSERT INTO menu (name, quantity) VALUES ('idk', 0 );
INSERT INTO menu (name, quantity) VALUES ('21', 0 );
INSERT INTO menu (name, quantity) VALUES ('stuff', 0 );
INSERT INTO menu (name, quantity) VALUES ('fierce', 0 );
INSERT INTO menu (name, quantity) VALUES ('undefined', 0 );
INSERT INTO menu (name, quantity) VALUES ('and a few', 0 );
INSERT INTO menu (name, quantity) VALUES ('more words', 0 );
INSERT INTO menu (name, quantity) VALUES ('Go here', 0 );
INSERT INTO menu (name, quantity) VALUES ('lala', 0 );
INSERT INTO menu (name, quantity) VALUES ('words', 0 );
INSERT INTO menu (name, quantity) VALUES ('words', 0 );
INSERT INTO menu (name, quantity) VALUES ('more words', 0 );
INSERT INTO menu (name, quantity) VALUES ('Blue', 0 );
INSERT INTO menu (name, quantity) VALUES ('Pink', 0 );
INSERT INTO menu (name, quantity) VALUES ('Green', 0 );
INSERT INTO menu (name, quantity) VALUES ('Orange', 0 );
